name: context-demo s
on: push
jobs: 
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: conext
        run: |
          echo "this is trigered by ${{github.actor}}" 
          echo "the repo is ${{github.repository}}"
      - name: print all
        run: echo "${{toJson(github)}}"